### ISSUE TITLE
请问这是简书网站的源代码还是您写的一个demo？

### ISSUE THREAD

**Issue by xiaoyaodev** [jeneser/jianshu#4]
请问这是简书网站的源代码还是您写的一个demo？
angular2重构的，我想看看

**Comment by jeneser** [comment]
这是我写的DEMO。还未完成，暂时停下来了。

**Comment by deepthan** [comment]
你好，看了你的文章 ‘部署Angular应用到Github pages’ 但还是不清楚怎么部署，可以加你qq请教下吗？我 1296936373，谢谢。
