### ISSUE TITLE
你好，我上传了angular应用但是页面只显示readme的内容

### ISSUE THREAD

**Issue by deepthan** [jeneser/jianshu#5]
按照你的方法打包了应用但是访问博客只显示readme的内容，我的仓库是https://github.com/deepthan/deepthan.github.io，
博客地址是：https://deepthan.github.io/deepthan.github.io/。
可以帮忙看下是怎么回事吗？谢谢。

**Comment by jeneser** [comment]
打包之后，本地访问是否正常？不正常则打包存在问题。
正常的话，检查Github pages的Url设置或`<base href="/">`配置是否有问题。
关于上传至pages参考[angular-cli-ghpages](https://github.com/angular-schule/angular-cli-ghpages)

**Comment by deepthan** [comment]
本地 ng server是正常的，打包
`ng build --prod --base-href "https://deepthan.github.io/deepthan.github.io/"`也成功了，之后ngh也显示成功。
检查Github pages的Url设置或<base href="/">配置是否有问题是在哪里呀？

**Comment by jeneser** [comment]
仓库名为`user.github.io`，URL为`https://deepthan.github.io/`是比较特殊的。可以尝试修改如下命令:
```
ng build --prod --base-href "https://deepthan.github.io/
```
如果仍存在问题，你可以新建一个测试的仓库，将代码部署上去，看是否仍存在问题。
eg: `https://jeneser.github.io/jianshu`

**Comment by deepthan** [comment]
你好，我的仓库名是deepthan.github.io，不是user.github,io，我又新建了一个仓库还是不行呀？
我的这个命令正确吗？
```ng build --prod --base-href "https://deepthan.github.io/deepthan.github.io/```

**Comment by deepthan** [comment]
可以给我你的qq吗？谢谢

**Comment by deepthan** [comment]
你好，我重新建了一个现在可以了，是设置里面的问题。
请问每次从本地提交代码都必须build一下再ngh吗？我直接ngh报错找不到路径。谢谢。
